### ISSUE TITLE
Consider adding a license file?!

### ISSUE THREAD

**Issue by pguth** [colingourlay/chooet#1]
Like in the past, quite nice stuff you do :) Maybe consider [adding a license](http://choosealicense.com/)?

**Comment by pguth** [comment]
[That](https://github.com/colingourlay/chooet/commit/5a006d338b69d266f946a1ba20bc783e8aa5e7c3) was fast, nice ❤️

**Comment by colingourlay** [comment]
Good call! https://github.com/colingourlay/chooet/commit/5a006d338b69d266f946a1ba20bc783e8aa5e7c3
